feat: i18n solution for prompts messages
vuejs/create-vue pull request #348
Opened 2023-09-25 14:42 UTC by luventa

Straightforward i18n solution for prompts messages

2023-09-25 14:57 UTC, luventa commented
ci test is blocked because of this:
![1695653758469](https://github.com/vuejs/create-vue/assets/19219477/a74358a2-0a83-4dd2-8a50-569e94def0d7)

2023-09-27 10:12 UTC, sodatea requested changes
Thanks! I've been thinking about this feature for a while.
However, I don't think it should be an additional option. Many people don't wanna bother selecting one at all.

Please make it implicit by reading the user's language setting from the environment variables.

2023-09-27 15:16 UTC, luventa commented
> Thanks! I've been thinking about this feature for a while. However, I don't think it should be an additional option. Many people don't wanna bother selecting one at all.
> 
> Please make it implicit by reading the user's language setting from the environment variables.

No problem, already updated. Is there anything that needs improvement?

2023-10-09 08:40 UTC, sodatea requested changes

2023-10-09 08:40 UTC, sodatea commented on index.ts
> +          active: language.needsTypeScript.toggleOptions[0],
This is hard to understand at a glance.
It needs to be more semantic, such as `toggleOptions['active']`. For now, all the `toggleOptions` are the same, so a global one should suffice, i.e. `language.defaultToggleOptions['active']`

2023-10-09 08:40 UTC, sodatea commented on index.ts
> +                : language.needsE2eTesting.selectOptions[1].desc,
Again, array indexes are hard to understand and maintain (when we need to sync modifications among different languages). Please use more semantic keys.

2023-10-09 08:40 UTC, sodatea commented on locales/zh-CN.json
> +    "message": "请输入项目名称:"
Please use the full-width colon character `：`
https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5#22-%E6%A0%87%E7%82%B9%E7%AC%A6%E5%8F%B7

2023-10-09 08:40 UTC, sodatea commented on locales/zh-CN.json
> +    "message": "非空，是否覆盖?",
Please use the full-width question mark `？`

2023-10-16 08:34 UTC, sodatea approved these changes
Thanks! Looks really good.

2023-10-16 08:34 UTC, merged