feat: add vscode config for ESLint
vuejs/create-vue pull request #467
Opened 2024-03-14 11:25 UTC by yoshi-pi

### Description
If the user picks ESLint, then suggest the ESLint .vscode extension, and add the settings.

**settings.json**
```
{
  "editor.codeActionsOnSave": {
    "source.fixAll": "explicit"
  }
}
```

**extensions.json**
```
{
  "recommendations": ["dbaeumer.vscode-eslint"]
}

```
### Related Issue
#466 

### Notes for Reviewers

-  **Created template/config/eslint** dedicated to ESLint's static settings, including .vscode/extensions.json and .vscode/settings.json.
- **Removed the existing code for adding the ESLint extension.**
- **Added code to merge Prettier settings into settings.json instead of overwriting them.**
- **Enabled generation of ESLint and Prettier snapshots.**

2024-03-14 12:44 UTC, Yordan-Ramchev reviewed
Looks good to me, except for **scripts/snapshot.mjs**

> This is going to make a lot of new snapshots
 
I think cexbrayat will provide better feedback for **scripts/snapshot.mjs** (for reference, https://github.com/vuejs/create-vue/pull/460#discussion_r1516419797).

2024-03-14 13:34 UTC, cexbrayat requested changes
Except the snapshot generation, LGTM, thanks for the PR.

2024-03-15 02:48 UTC, yoshi-pi commented on scripts/snapshot.mjs
> +  ['eslint', 'eslint-with-prettier'],
Moved eslint and eslint-with-prettier as separate features based on https://github.com/vuejs/create-vue/pull/460#discussion_r1516419797

2024-03-18 14:10 UTC, cexbrayat approved these changes

2024-03-18 16:08 UTC, Yordan-Ramchev approved these changes

2024-03-19 07:39 UTC, sodatea approved these changes

2024-03-19 07:39 UTC, merged