feat: use `??` instead of `||`, drop Node.js 12 support
vuejs/create-vue pull request #78
Opened 2022-03-06 07:55 UTC by zhhbstudio

按照注释使用空值合并运算符（??）替换逻辑或操作符（||），提高代码可读性。

2022-03-10 06:53 UTC, sodatea requested changes
谢谢 PR！不过有一个小问题需要修改一下

2022-03-10 06:53 UTC, sodatea commented on index.js
> +          onState: (state) => (targetDir = String(state.value).trim() ?? defaultProjectName)
这里 `String().trim()` 肯定不会是 `undefined`，至多是 `''`，所以不能用 `??`

2022-03-10 12:54 UTC, zhhbstudio commented on index.js
> +          onState: (state) => (targetDir = String(state.value).trim() ?? defaultProjectName)
好的，非常感谢，是我没考虑到。

2022-03-11 08:02 UTC, sodatea approved these changes

2022-03-11 08:02 UTC, merged